Objetivo 0.Redactando
DarckMonster/PCscrap pull request #1
Opened 2023-09-20 11:54 UTC by DarckMonster

2023-09-20 12:22 UTC, JJ commented
Por favor, sigue las instrucciones [del guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) que incluye, para empezar, una lista de comprobación y el formato del título. Aprovecha para revisar si lo enviado es adecuado para la asignatura. Cuando termines, solicita revisión usando un comentario aquí o asignándome como reviewer.

2023-09-20 15:14 UTC, DarckMonster commented
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
	 Sí, llevo bastante tiempo montando ordenadores a diferentes personas.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
   	 Si, tenemos que hacer scrapping de datos de webs y almacenarlos para su uso.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
    	 Sí, es la comprobación de muchos productos en disitintas webs.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
	 El usuario esencilamente elige los productos para comprobar su precio.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-20 15:43 UTC, JJ commented
Como indica el guión, la lista de comprobación tiene que estar en el cuerpo del PR, no en un comentario. Como te he dicho también, conviene que desde el objetivo 0 configuréis correctamente el avatar en vez de usar el que se da por omisión.

2023-09-20 15:44 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí, llevo bastante tiempo montando ordenadores a diferentes personas.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Si, tenemos que hacer scrapping de datos de webs y almacenarlos para su uso.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Sí, es la comprobación de muchos productos en disitintas webs.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?

De la misma forma, os rogaría que no marcárais lo que no habéis hecho. Nos ahorraremos los dos trabajo.

2023-09-20 17:49 UTC, DarckMonster commented
Si, perdone, creo que ya está bien. ¿Vio mi idea de problema?

2023-09-21 05:30 UTC, JJ commented
> Si, perdone, creo que ya está bien. ¿Vio mi idea de problema?

La lista de comprobación sigue sin estar en el cuerpo del PR. En general, si no se ha seguido *la forma* de la entrega, es muy probable que *el contenido* de la entrega tampoco sea correcto. Así que te animo a revisarlo, consultando si es necesario [los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md) para tratar de evitarlos.

2023-09-21 11:32 UTC, JJ requested changes
Sería conveniente, una vez más, que pongas explícitamente como has seguido una metodología como *design thinking* para superar este objetivo. Inclúyelo en el PR, y cuando lo hayas hecho pide la revisión explícitamente.

2023-09-21 11:32 UTC, JJ commented on README.md
> +Un informático que se dedica a montar ordenadores quiere buscar componentes de mejor precio en internet.
Por favor, revisa en el guión lo que es aceptable o no como problema y descripción del mismo. En general, una sola frase va a ser totalmente inadecuada para iniciar cualquier desarrollo.

2023-09-21 16:57 UTC, DarckMonster commented
Durante la clase de hoy he realizado el juego de rol que me ha ayudado a enfocar mejor la búsqueda del problema. Poniendome en el papel de un usuario con el problema  y con la ayuda de un compañero he podido aclarar más las ideas.

2023-09-21 18:01 UTC, JJ requested changes
Aunque el contexto y el problema está más o menos bien especificado, debes tratar de aclarar realmente de qué problema se trata. Si la información está claramente estructurada y es fácil de buscar, ¿se trata de predecir? Si no está estructurada, ¿se trata de extraer esa información?

2023-09-21 18:01 UTC, JJ commented on README.md
> +Una persona que se dedica a montar ordenadores pasa demasiado tiempo mirando en distintas webs para encontrar la mejor para comprar un componente. Además no sabe si se encuentra en un mal momento par
¿Cuál es específicamente el problema? ¿Extraer información de las webs, donde está semiestructurada?

2023-09-21 18:19 UTC, DarckMonster commented on README.md
> +Una persona que se dedica a montar ordenadores pasa demasiado tiempo mirando en distintas webs para encontrar la mejor para comprar un componente. Además no sabe si se encuentra en un mal momento par
Primero es tener un historial de precios diarios para poder predecir el mejor momento para comprar un tipo de componentes, además facilitar la colección de información por la variedad de tiendas online y distintos modelos de cada componente ya que tenemos esa información. 
Yo mismo tengo este problema, gente que quiere comprar piezas le tengo que decir que no porque ciertos componentes están caros en el momento y es mejor esperar a que bajen, quiero saber cuando se avecina la oferta que permita comprar barato.

2023-09-21 18:32 UTC, JJ commented on README.md
> +Una persona que se dedica a montar ordenadores pasa demasiado tiempo mirando en distintas webs para encontrar la mejor para comprar un componente. Además no sabe si se encuentra en un mal momento par
No puedes tener un historial si la información es difícil de extraer; y si asumes que lo tienes porque quieres resolver otro problema, tienes que programar un algoritmo de predicción, entrenarlo y demás. Algo que se escapa de esta asignatura.
Estás suponiendo también que las ofertas son predecibles con el historial, lo que yo no veo, la verdad.
En resumen: si el problema es extraer la información, *sí* sería un problema aceptable, como pone en el guión. Lo que quieras hacer con esa información sería una historia de usuario más avanzada, pero la lógica de negocio estaría relacionada con extraer la información, es decir, mirar un URL y de ahí sacar los precios identificando marca, modelo, y precio.
Ya te digo de todas formas que en general todo lo que sea scraping es un arte arcano, y la mayoría de las webs van a usar todo tipo de trucos para que esto no se pueda hacer. Desde poner el precio como una imagen, hasta usar diferentes elementos HTML cada vez que rendericen la página, hasta todo tipo de conjuros arcanos. Scraping es un arte arcano, y te lo digo yo que lo llevo haciendo desde hace 25 años o más.

2023-09-21 18:51 UTC, JJ commented on README.md
> +Una persona que se dedica a montar ordenadores pasa demasiado tiempo mirando en distintas webs para encontrar la mejor para comprar un componente. Además no sabe si se encuentra en un mal momento par
Insisto, entonces el problema es extrar la información mediante scraping. Sólo asegúrate de que realmente es posible hacerlo y sobre todo cuando hagas pruebas o empieces a escribir código bájate un par de páginas para hacer las pruebas (sin incluirlas en el repo, porque es ilegal) y trabaja siempre sobre las páginas descargadas *nunca* sobre las páginas online.
Como para hacer tests tendrás que tener las páginas, alternativamente puedes crear una representación de las páginas intermedia que sí puedas almacenar (por ejemplo, extraes la línea de texto y almacenas en el repo sólo esa línea de texto).
Como te digo, te podría contar unas cuantas batallitas sobre scraping (personales y otras que he oído). Así que siempre hay que extremar la precaución.

2023-09-21 18:56 UTC, DarckMonster commented on README.md
> +Una persona que se dedica a montar ordenadores pasa demasiado tiempo mirando en distintas webs para encontrar la mejor para comprar un componente. Además no sabe si se encuentra en un mal momento par
Genial. Por ejemplo un amigo me ayudó a hacer scraping de tarjetas gráfiicas en pccomponentes y pudimos hacerlo pero tuvimos el error de hacerlo directamente a la página web como dice y tras unos intentos me bloqearon el acceso. Descargar la página podría haberlo solucionado. Pero el scraping funcionaba.

2023-09-22 12:00 UTC, DarckMonster commented
Listo

2023-09-22 12:25 UTC, JJ approved these changes
👍 Por favor, no seas tan conciso. Di en qué hay que estructurarla, aunque esté implícito que hay que hacerlo para hacer esas comparaciones. En todo caso lo tendrás que hacer en el objetivo 1

2023-10-05 10:54 UTC, merged