[IV-23-24] Objetivo 3
DarckMonster/PCscrap pull request #27
Opened 2023-11-16 09:03 UTC by DarckMonster

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-20 10:53 UTC, LuciaAnsino reviewed
Te recomiendo que investigues un poco más sobre otros gestores de dependencias y de tareas y luego ya uses la elección que más se ajuste a los criterios que has debido de indicar.

2023-11-20 10:53 UTC, LuciaAnsino commented on docs/gestor-dependencias.md
> +# Gestor de dependencias
Sería conveniente que indicaras los criterios que has aplicado para seleccionar el gestor de dependencias.

2023-11-20 10:53 UTC, LuciaAnsino commented on docs/runtime.md
> +# Runtime para TypeScript
Al igual que para el gestor de dependencias es conveniente que indiques los criterios de selección que has usado.

2023-11-20 10:53 UTC, LuciaAnsino commented on docs/task-manager.md
> +# Task Manager
Al igual que antes también deberías poner los criterios de selección usados

2023-11-23 11:58 UTC, DarckMonster commented on docs/gestor-dependencias.md
> +# Gestor de dependencias
resuelto en facb35f3faa8450da3ae1678f054ed00245de18f

2023-11-23 11:58 UTC, DarckMonster commented on docs/task-manager.md
> +# Task Manager
resuelto en facb35f3faa8450da3ae1678f054ed00245de18f

2023-11-23 11:58 UTC, DarckMonster commented on docs/runtime.md
> +# Runtime para TypeScript
resuelto en facb35f3faa8450da3ae1678f054ed00245de18f

2023-11-23 17:30 UTC, LuciaAnsino requested changes

2023-11-23 17:30 UTC, LuciaAnsino commented on docs/runtime.md
> +* Estoy buscando un runtime que sea rápido y moderno, pero que además sea totalmente compatible con **TypeScript**.
Si como indicas en la linea 19 la popularidad de deno y node entre los alumnos te ayudo a decantarte debes incluir eso también en los criterios seguidos.

2023-11-23 17:33 UTC, DarckMonster commented on docs/runtime.md
> +* Estoy buscando un runtime que sea rápido y moderno, pero que además sea totalmente compatible con **TypeScript**.
Bueno, esto lo escribí aparte como letra pequeña pero no debería ser un criterio a tener en cuenta para un caso real. Quise dejarlo fuuera y solo mencionarlo.

2023-11-24 09:03 UTC, LuciaAnsino requested changes
De acuerdo

2023-11-24 09:03 UTC, LuciaAnsino commented on docs/runtime.md
> +* Estoy buscando un runtime que sea rápido y moderno, pero que además sea totalmente compatible con **TypeScript**.
De acuerdo, aunque sea solo un comentario si es algo que has tenido en cuenta se debería de indicar como criterio, si no parece real puedes ponerlo en los criterios de alguna otra forma que parezca más real.

2023-11-27 11:46 UTC, DarckMonster commented on docs/runtime.md
> +* Estoy buscando un runtime que sea rápido y moderno, pero que además sea totalmente compatible con **TypeScript**.
Resuelto en facb35f3faa8450da3ae1678f054ed00245de18f

2023-11-27 11:59 UTC, LuciaAnsino approved these changes

2023-11-27 17:28 UTC, DarckMonster commented
@JJ tengo una revisión aprobaada

2023-11-27 17:30 UTC, JJ approved these changes
:+1: y muchas gracias a @LuciaAnsino por sus revisiones.

2023-11-27 17:32 UTC, merged