[IV-23-24] Objetivo 5
DarckMonster/PCscrap pull request #50
Opened 2024-01-05 12:07 UTC by DarckMonster

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2024-01-09 19:07 UTC, DarckMonster commented
07929fcbaae3061050855f8de8c07d4e6b45f9c9 commit por error :no_mouth:

2024-01-10 18:07 UTC, Enaraque reviewed
Hola! Por lo general lo he visto todo bien pero te he comentado una cosa que se podría mejorar.

2024-01-10 18:07 UTC, Enaraque commented on Dockerfile
> +LABEL mainteiner="juanfcv2001@correo.ugr.es"
Puedes definir una única LABEL para ambos. 
```
LABEL version="5.0.0" \
     mainteiner="juanfcv2001@correo.ugr.es"
```

2024-01-10 18:09 UTC, DarckMonster commented on Dockerfile
> +LABEL mainteiner="juanfcv2001@correo.ugr.es"
Ok gracias!

2024-01-10 18:11 UTC, DarckMonster commented on Dockerfile
> +LABEL mainteiner="juanfcv2001@correo.ugr.es"
Todo correcto, funciona

2024-01-10 18:13 UTC, Enaraque commented
En lo correspondiente a los commits, intenta cerrar todos los issues con ellos ya que hay algunos donde haces referencia a algunos de ellos pero no los cierras después, como en #56 o #59 🫡

2024-01-10 18:15 UTC, Enaraque commented on Dockerfile
> +LABEL mainteiner="juanfcv2001@correo.ugr.es"
🤘🤘

2024-01-10 18:20 UTC, DarckMonster commented
> En lo correspondiente a los commits, intenta cerrar todos los issues con ellos ya que hay algunos donde haces referencia a algunos de ellos pero no los cierras después, como en #56 o #59 🫡

CIerto, 🫡, en los otros pr me ha pasado mucho, ya he aprendido jaj

2024-01-10 18:54 UTC, carlotiii30 requested changes
Buenas! Creo que sería conveniente que justificaras un poco más la elección de la imagen y de su versión. Te he dejado un par de comentarios para ayudarte con esto.

2024-01-10 18:54 UTC, carlotiii30 commented on docs/eleccion-imagen.md
> +* Cierto rendimiento, así que buscaremos que la imagen sea ligera para evitar que se sobrecargue.
¿Has medido el tamaño de las imágenes?

2024-01-10 18:54 UTC, carlotiii30 commented on docs/eleccion-imagen.md
> +* Lo más importante es que podamos ejecutar `bun` en la imagen, es decir, que sea compatible con nuestro toolkit.
Entonces, esto no es un criterio, si no, más bien, un requisito, ¿no?

2024-01-10 18:54 UTC, carlotiii30 commented on docs/eleccion-imagen.md
> +* Cierto rendimiento, así que buscaremos que la imagen sea ligera para evitar que se sobrecargue.
En realidad, creo que este es el único "criterio" que podría diferenciar unos de otros. Tanto mantenimiento como ejecutar `bun` son requisitos necesarios para que se tengan en cuenta.

2024-01-10 20:06 UTC, DarckMonster commented on docs/eleccion-imagen.md
> +* Lo más importante es que podamos ejecutar `bun` en la imagen, es decir, que sea compatible con nuestro toolkit.
Es cierto, realmente el criterio que he usado es que vienen con bun preinstalado

2024-01-10 20:07 UTC, DarckMonster commented on docs/eleccion-imagen.md
> +* Cierto rendimiento, así que buscaremos que la imagen sea ligera para evitar que se sobrecargue.
Buesqué en internet y vi que por su descripción slim debe ser la más ligera pero no probé a hacer las imágnes.

2024-01-10 20:11 UTC, DarckMonster commented on docs/eleccion-imagen.md
> +* Lo más importante es que podamos ejecutar `bun` en la imagen, es decir, que sea compatible con nuestro toolkit.
resuelto en eb55dacf8ae4ba9f55407ca46ae2d59c932cc34d

2024-01-10 20:47 UTC, carlotiii30 approved these changes
Gracias por las correcciones y las explicaciones tan rápidas. Lo veo bien.

2024-01-10 21:36 UTC, Enaraque commented
Yo lo veo listo para revisión también 👌

2024-01-10 21:36 UTC, Enaraque approved these changes

2024-01-11 08:56 UTC, DarckMonster commented
@JJ dos correcciones positivas

2024-01-11 09:30 UTC, JJ approved these changes
:+1: 
Muchas gracias a @Enaraque y @carlotiii30 por las revisiones.

2024-01-28 21:26 UTC, merged