añadido IV.yaml
DarckMonster/PCscrap pull request #9
Opened 2023-10-06 11:54 UTC by spmanolo

2023-10-06 11:56 UTC, DarckMonster commented
Hola, encantado de trabajar contigo, te asigno el M0. :smile:

2023-10-21 20:22 UTC, spmanolo commented
Hola @DarckMonster, he modificado un poco la estructura comentada en #10 después de darle unas vueltas. Acabo de crear la nueva estructura, cuando puedas échale un vistazo y me comentas :smile:

2023-10-23 09:01 UTC, DarckMonster commented
> Hola @DarckMonster, he modificado un poco la estructura comentada en #10 después de darle unas vueltas. Acabo de crear la nueva estructura, cuando puedas échale un vistazo y me comentas 😄

Tras revisar el código has hecho un buen trabajo, ahora te comento sobre el código. :ok_hand:

2023-10-27 12:00 UTC, spmanolo commented
> > Hola @DarckMonster, he modificado un poco la estructura comentada en #10 después de darle unas vueltas. Acabo de crear la nueva estructura, cuando puedas échale un vistazo y me comentas 😄
> 
> Tras revisar el código has hecho un buen trabajo, ahora te comento sobre el código. 👌

Hola! Cuando puedas revisame el código para poder mencionar al profesor y que lo termine de revisar.
Y también asigna los issues al milestone 0.
Gracias! :smile:

2023-10-27 12:05 UTC, DarckMonster commented
> > > Hola @DarckMonster, he modificado un poco la estructura comentada en #10 después de darle unas vueltas. Acabo de crear la nueva estructura, cuando puedas échale un vistazo y me comentas 😄
> > 
> > 
> > Tras revisar el código has hecho un buen trabajo, ahora te comento sobre el código. 👌
> 
> Hola! Cuando puedas revisame el código para poder mencionar al profesor y que lo termine de revisar. Y también asigna los issues al milestone 0. Gracias! 😄

Si, ya te asigné al M0 los issues. Ya te escribí sobre el código mencionandolo aqui en el PR.

2023-10-27 15:09 UTC, spmanolo commented
Perfecto, gracias! @JJ listo para revisión.

2023-10-27 15:12 UTC, spmanolo commented
@DarckMonster Por cierto no olvides poner cuando puedas aquí tu lista de comprobación, la del propietario del repo.

2023-10-27 15:24 UTC, JJ commented
Sí, por favor, aprobad explícitamente y en el mensaje de aprobación  seguid la lista de comprobación.

2023-10-30 11:09 UTC, spmanolo commented
Vale, @DarckMonster cuando puedas apruebame el código porfa :)

2023-10-30 11:26 UTC, DarckMonster commented
> Vale, @DarckMonster cuando puedas apruebame el código porfa :)

No ves una review de una linea de código?

2023-10-30 14:14 UTC, spmanolo commented
> > Vale, @DarckMonster cuando puedas apruebame el código porfa :)
> 
> No ves una review de una linea de código?

No la veo

2023-10-30 14:15 UTC, spmanolo commented
@DarckMonster Creo que tienes que confirmar los cambios en el botón de `Review Changes`

2023-10-30 15:53 UTC, spmanolo commented on src/componente.ts
> +  precioMax: number;
Es el precio máximo que se quiere pagar por un componente, esto lo determina el usuario diciendo que busca un componente dentro de una horquilla de precios [precioMin, precioMax].

2023-10-30 15:53 UTC, spmanolo commented
> @spmanolo disculpa por el fallo! 😞

No te preocupes :)

2023-10-30 16:13 UTC, DarckMonster commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-10-30 16:23 UTC, spmanolo commented
Gracias! 😄 @JJ Listo para revisión.

2023-10-30 17:27 UTC, JJ requested changes
Por favor, tratad de ajustaros a las buenas prácticas tanto en la resolución de los comentarios como en el nombre de los ficheros.

2023-10-30 17:27 UTC, JJ commented on IV.yaml
> +entidad: src/pcScrap.ts
Como he repetido varias veces en clase, las buenas prácticas desaconsejan que se usen nombres de ficheros que incluyan mayúsculas.

2023-10-30 18:04 UTC, spmanolo commented
@JJ He modificado el nombre de los ficheros para ajustarme a las buenas prácticas.

2023-10-30 18:19 UTC, JJ commented
La mayoría de los commits "añadido x" no se ajustan a las buenas prácticas, como se indica en [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#errores-frecuentes-objetivo-2). 

> Poner en el mensaje de commit "Solución xx". Decir que es la solución no contribuye a entender por qué se trata de la solución. Tampoco "Añadido x". El mensaje debe añadir información a lo que ya es evidente, porque en la información del mismo se ve claramente qué se ha añadido o modificado. Debe explicar por qué se ha tomado esa decisión específica de crear ese objeto para resolver el problema y no otro.

Los mensajes de commit no se pueden modificar, pero no seguir las buenas prácticas en este aspecto generalmente es indicación de que no se han seguido en otros casos y que por tanto hará falta otra ronda de revisión. Te agradeceré que conozcas las buenas prácticas y las sigas en ese caso (y en el futuro en tu repo)

2023-10-30 18:23 UTC, JJ requested changes
DAdo que el código no se ha añadido al repo enlazando el problema (issue) con el que se está trabajando, es inválido y hay que empezar de nuevo. Un modelo consiste en la creación de una serie de problemas en issues, y su resolución paso a paso mediante código, expresando claramente en cada momento qué opciones se han elegido y por qué se ha optado por esa solución.
Es lo esencial de este objetivo. Te agradecería que trataras de seguir esa metodología, porque esencialmente la ingeniería del software consiste en aprender a usar metodologías.

2023-10-30 18:23 UTC, JJ commented on src/componente.ts
> +  setPrecioMax(precioMax: number) {
Por favor, lee [en el fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido) sobre getters, setters y constructores.
En general, en este milestone se trata de establecer un modelo. No parece que añadir setters y getters triviales, así como constructores triviales, contribuya información adicional a ese modelo.

2023-10-30 18:23 UTC, JJ commented on src/pc_scrap.ts
> +import { Componente } from "./componente";
El commit que crea esta clase es este https://github.com/DarckMonster/PCscrap/commit/0d4718bccd79e94cd0129bbe9344badfeba1b54b
No hace referencia a ningún issue, luego el código creado es imposible de evaluar y por tanto inválido. Bórralo y comienza de nuevo, usando ahora los issues creados.

2023-10-30 18:38 UTC, spmanolo commented on src/pc_scrap.ts
> +import { Componente } from "./componente";
Ese commit hace referencia al issue #13 no?

2023-10-30 18:45 UTC, JJ commented on src/pc_scrap.ts
> +import { Componente } from "./componente";
OK, fallo mío. Por eso hay que ponerlo en la primera línea...

2023-10-30 18:51 UTC, JJ requested changes
En este caso, creo que lo mejor sería replantear los issues desde el principio porque no se centran en resolver el problema, que es principalmente extraer información de una fuente poco estructurada.

2023-10-30 18:51 UTC, JJ commented on src/pc_scrap.ts
> +class PcScrap {
Aparte del nombre (que deberías escribir correctamente) no hay nada en este modelo que lo relacione con el scraping, que es el tema principal del issue #13

2023-11-01 14:04 UTC, spmanolo commented
Debido a todos los errores, voy a cerrar este PR y comenzar de nuevo con los issues y la propuesta. @DarckMonster perdón si tardo un poco en hacer esto.

2023-11-01 14:04 UTC, closed without merging

2023-11-01 18:15 UTC, JJ commented
Lo mejor sería que dejaras solo el iv.yaml y fusionaras esto cerrando el ticket del lenguaje. Cuando crees la rama ya tienes eso hecho, y si @DarckMonster quiere seguir al objetivo siguiente puede sacar una rama directamente de lo fusionado.